version: "3.8"

networks:
  flipNetwork:
    name: flipNetwork

volumes:
  dappVolume:
    driver: local
    driver_opts:
      device: ./project/
      o: bind
      type: none

services:
  flip:
    build:
      context: .
      dockerfile: ./whaleSetup/Dockerfile
    container_name: flip
    # depends_on:
    #   - backend
    ports:
      - "3000:3000"
    volumes:
      - ./project/:/usr/src/app/
    # env_file:
    #   - .env
    networks:
      - flipNetwork
    restart: always